---
- name: Create directories for elasticsearch
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: 1000
    group: 1000
    mode: 0777
    recurse: yes
  with_items:
    - '{{ volume_directory }}/logging/elasticsearch/data'

- name: Set max_map_count to minimum value for elasticsearch
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present
