---
- name: Install required python modules for Docker
  pip:
    name: "{{ item.name }}"
    state: present
  with_items:
  - { name: jsondiff }

- name: Install required python modules for Docker (with specific versions)
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
  with_items:
  - { name: docker-py, version: 1.10.6 }

- name: Create an overlay network
  docker_network:
    name: '{{ docker_network_name }}'
    driver: overlay
    state: present

- name: Remove logging stack
  docker_stack:
    name: logging
    state: absent

- import_tasks: elasticsearch.yml

- import_tasks: filebeat.yml

- name: Write out docker-compose-logging.yml template
  template:
    src: docker-compose-logging.yml.j2
    dest: '{{ temporary_directory }}/docker-compose-logging.yml'

- name: Deploy logging stack swarm
  docker_stack:
    state: present
    name: logging
    compose:
      - "{{ temporary_directory }}/docker-compose-logging.yml"
    with_registry_auth: yes