---
- name: Install required python modules for docker
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
  with_items:
  - { name: docker-py, version: 1.10.6 }

- name: Create an overlay network
  docker_network:
    name: '{{ docker_network_name }}'
    driver: overlay
    state: present

- import_tasks: elasticsearch.yml

- import_tasks: filebeat.yml

- name: Write out docker-compose-logging.yml template
  template:
    src: docker-compose-logging.yml.j2
    dest: '{{ temporary_directory }}/docker-compose-logging.yml'

- name: Deploy logging stack to swarm
  command: docker stack deploy --with-registry-auth --compose-file {{ temporary_directory }}/docker-compose-logging.yml logging